store/store_frontend/Controllers/GamingController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using StoreFrontendFinal.Models;
using StoreFrontendFinal.Models.Utils;
using System.Collections.Generic;

namespace StoreFrontendFinal.Controllers
{
	public class GamingController : Controller
	{
        private readonly ILogger _logger;
		private readonly ProductService productService;

        public GamingController(ILogger<GamingController> logger)
        {
            _logger = logger;
			productService = new ProductService();
        }

        public ActionResult Playstation()
		{
            var products = GetProducts("Playstation");
            _logger.LogInformation("-> " + productService.GetServiceUrl());
			if (products is RedirectToActionResult)
			{
				return (ActionResult)products;
			}

			return View(products);
		}

        public ActionResult Xbox()
        {
            var products = GetProducts("Xbox");
            if (products is RedirectToActionResult)
            {
                return (ActionResult)products;
            }

            return View(products);
        }

        public ActionResult Nintendo()
        {
            var products = GetProducts("Nintendo");
            if (products is RedirectToActionResult)
            {
                return (ActionResult)products;
            }

            return View(products);
        }


        public ActionResult Details(int id)
        {
            // Get Product by its id
            var product = productService.GetProduct(id);
            if (product == null)
            {
                var msg = string.Format("Problem fetching product id = {0} on the backend side.", id);
                _logger.LogWarning(msg);
                return RedirectToAction("Error", "Home", new { errorMessage = msg });
            }

            // Get Product's Opinions, using product's id
            var opinions = productService.GetProductOpinions(id);
            if (opinions == null)
            {
                var msg = string.Format("Problem fetching opinions of product = {0} on the backend side.", id);
                _logger.LogWarning(msg);
                return RedirectToAction("Error", "Home", new { errorMessage = msg });
            }

            // Return a view with Product and its Opinions
            return View("Details", new ProductAndOpinionsVM(product, opinions));
        }

        public ActionResult PostOpinion(int? productId)
        {
            // check if a productId was not provied
            if (productId == null)
            {
                var msg = "Invalid product id";
                _logger.LogInformation(msg);
                return RedirectToAction("Error", "Home", new { errorMessage = msg });
            }

            // check if user is logged in
            if (!AuthenticationHelper.IsLoggedIn(HttpContext))
            {
                _logger.LogInformation("User is not logged in");
                return RedirectToAction("Login", "Login");
            }

            // Get product
            Product? product = productService.GetProduct((int)productId);
            if (product == null)
            {
                _logger.LogInformation("There is no product with id = {0}", productId);
                return RedirectToAction("Login", "Login");
            }

            // Return view with a Product and a blank Opinion (ProductOpinionVM)
            return View(
                nameof(PostOpinion),
                new ProductOpinionVM { ProductId = product.id, ProductImage = product.image, ProductName = product.name });
        }

        [HttpPost]
        public ActionResult PostOpinion(ProductOpinionVM model)
        {
            // check validity of Viewmodel
            if (!ModelState.IsValid)
            {
                _logger.LogInformation("User has given an invalid model");
                return View(model);
            }

            // check model's fields
            if (model.Description == null || model.Title == null)
            {
                var msg = "Invalid description or title " + model.ToString();
                _logger.LogInformation(msg);
                return RedirectToAction("Error", "Home", new { errorMessage = msg });
            }

            // Post new opinion
            bool postOpinionOk = productService.PostOpinion(model.ProductId, model.Title, model.Description, model.Rating);
            if (!postOpinionOk)
            {
                var msg = string.Format("There was problem adding an opinion for product={0} on the Products Service side.", model.ProductId);
                _logger.LogWarning(msg);
                return RedirectToAction("Error", "Home", new { errorMessage = msg });
            }

            // Return view with a Product and a blank Opinion (ProductOpinionVM)
            return RedirectToAction(nameof(Details), new { id = model.ProductId });
        }

        [NonAction]
        private Object GetProducts(string categoryName)
        {
            var category = productService.GetCategory(categoryName);
            if (category == null)
            {
                _logger.LogWarning("Category {0} doesn't exist!", categoryName);
                return new List<Product>();
            }

            var products = productService.GetProducts(category);
            if (products == null)
            {
                _logger.LogWarning("Problem fetching product from category {0} on the backend side.",
                    categoryName);
                return new List<Product>();
            }
            foreach (var prod in products)
            {
                prod.image = productService.GetServiceUrl() + prod.image;
            }

            return products;
        }
    }
}

store/store_frontend/Views/Gaming/Details.cshtml
@model StoreFrontendFinal.Models.ProductAndOpinionsVM
@using StoreFrontendFinal.Models.Utils
@{
    ViewData["Title"] = "Details";

    int quantity = 1;
    string imageUrl = Model.Product.image;

}

<style>
    #opinion-button {
        background-color: darkslateblue;
        border-color: darkslateblue;
        margin-bottom: 10px;
    }
    #opinion-button:hover {
        background-color: #412c66;
        border-color: #412c66;
    }
</style>

<main>
    <div class="product-detail">
        <div class="product-image">
            <img src="@imageUrl" alt="Product Image" width="400">
        </div>
        <div class="product-info">
            <h3>@Html.DisplayFor(model => model.Product.name)</h3>
            <p class="product-price">@Html.DisplayFor(model => model.Product.price)€</p>
            <form action="@Url.Action("AddToCart", "Purchase", new { productId = Model.Product.id, quantity = quantity })" method="post">
                <label for="product-quantity">Quantity:</label>
                <input id="product-quantity" type="number" name="quantity" value="4" min="1" max="10">
                <button type="submit" class="btn btn-primary">
                    Buy
                </button>
            </form>
        </div>
    </div>
    <div class="product-description" style="margin-bottom: 30px">
        <h3>Description</h3>
        <p>@Html.DisplayFor(model => model.Product.description)</p>
        <ul>

            @if (Model.Product.color != null && Model.Product.color.Length > 0)
                {
                <li><b>Color:</b> @Html.DisplayFor(model => model.Product.color)</li>
                }
            @if (Model.Product.size != null && Model.Product.size.Length > 0)
                {
                <li><b>Size:</b> @Html.DisplayFor(model => model.Product.size)</li>
                }

            <li>
                <b>Brand:</b>
                @{
                    @Html.DisplayFor(model => model.Product.brand.name);
                }
            </li>
            <li>
                <b>About brand:</b>
                @{
                    @Html.DisplayFor(model => model.Product.brand.description)
                }
            </li>
        </ul>
    </div>
    <div class="product-description">
        <h3>Opinions</h3>
        <div>
            <button id="opinion-button" type="submit" onclick="location.href='@Url.Action("PostOpinion", "Gaming", new { productId = Model.Product.id })'" class="btn btn-danger">
                <i class="fa fa-plus"></i>
                Post an opinion
            </button>
        </div>
        @{if (Model.Opinions.Count() <= 0) {
                <p style="font-style: italic; color:#666666">There are no opinions for this product yet. Want to be the first posting an opinion?</p>
            }
        else {
        <table>
            <thead>
                <tr>
                    <th></th>
                    <th>
                        <div style="white-space: nowrap;">
                            Number of stars
                        </div>
                    </th>
                    <th></th>
                    <th>
                        Title
                    </th>
                    <th></th>
                    <th>
                        Description
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Opinions)
                 {
                    <tr>
                        <td></td>
                        <td>
                            <div style="white-space: nowrap;">
                                @{
                                    for (int i = 0; i < item.number_of_stars; i++)
                                    {
                                        <img src="~/images/star.png" alt="star" style="width:20px; height:20px" />
                                    }
                                }
                            </div>
                        </td>
                        <td></td>
                        <td>
                            @Html.DisplayFor(modelItem => item.title)
                        </td>
                        <td></td>
                        <td>
                            @Html.DisplayFor(modelItem => item.description)
                        </td>
                        <td></td>
                    </tr>
                 }
            </tbody>
        </table>
        }
    }
    </div>
</main>

<script>document.getElementById("product-quantity")
                .addEventListener("change", function () {
                    @quantity = document.getElementById("quantity").value;
                    print("hello! @quantity");
                });
</script>



store/store_frontend/Views/Gaming/Nintendo.cshtml
@model IEnumerable<StoreFrontendFinal.Models.Product>

@{
    ViewData["Title"] = "Nintendo";
}

<div class="image-container">
    <img src="~/images/banner-nintendo.jpg" alt="Image description">
    <div class="image-text">
        <p>@ViewData["Title"]</p>
    </div>
</div>


<table>
    <thead>
        <tr>
            <th></th>
            <th>
                Picture
            </th>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.brand)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td></td>
                <td>
                    <img src="@item.image" width="100" height="100" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.price)€
                </td>
                <td>
                    @if (item.brand != null)
                    {
                        @Html.DisplayFor(modelItem => item.brand.name)
                    }
                </td>
                <td>
                    <button class="view-btn" onclick="location.href = '@Url.ActionLink("Details", "Gaming", new { id=item.id })'">
                        <i class="fa fa-eye"></i>
                        View
                    </button>
                </td>
            </tr>
        }
    </tbody>
</table>

store/store_frontend/Views/Gaming/Playstation.cshtml
@model IEnumerable<StoreFrontendFinal.Models.Product>

@{
    ViewData["Title"] = "PlayStation";
}

<div class="image-container">
    <img src="~/images/banner-playstation.jpg" alt="Image description">
    <div class="image-text">
        <p>@ViewData["Title"]</p>
    </div>
</div>


<table>
    <thead>
        <tr>
            <th></th>
            <th>
                Picture
            </th>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.brand)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td></td>
                <td>
                    <img src="@item.image" width="100" height="100"/>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.price)€
                </td>
                <td>
                    @if (item.brand != null)
                    {
                        @Html.DisplayFor(modelItem => item.brand.name)
                    }
                </td>
                <td>
                    <button class="view-btn" onclick="location.href = '@Url.ActionLink("Details", "Gaming", new { id=item.id })'">
                        <i class="fa fa-eye"></i>
                        View
                    </button>
                </td>
            </tr>
        }
    </tbody>
</table>

store/store_frontend/Views/Gaming/PostOpinion.cshtml
@model ProductOpinionVM

@{
        ViewBag.Title = "Product Review";
}

<div class="opinion">
    <div class="opinion-header">
        <h1>Product Review</h1>
    </div>
    <div class="opinion-body">
        <form method="post">
            <div class="opinion-form">
                <div class="form-group" style="margin-bottom: 20px">
                    <label for="productName"><b>Product</b> </label>
                    @Model.ProductName
                </div>
                <img src="@Model.ProductImage" width="200" height="100" style="margin-bottom: 20px" />
                <div class="form-group-opinion">
                    @Html.LabelFor(model => model.Rating, new { @class = "control-label" })
                    @Html.DropDownListFor(model => model.Rating, new SelectList(new List<int> { 1, 2, 3, 4, 5 }, 1), new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
                </div>
                <div class="form-group-opinion">
                    @Html.LabelFor(model => model.Title, new { @class = "control-label" })
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>
                <div class="form-group-opinion">
                    @Html.LabelFor(model => model.Description, new { @class = "control-label" })
                    @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.ProductId, Model.ProductId)
                    @Html.HiddenFor(model => model.ProductName, Model.ProductName)
                    @Html.HiddenFor(model => model.ProductImage, Model.ProductImage)
                </div>
                <div class="form-group" style="margin-top: 20px">
                    <button type="submit" class="btn btn-primary">Post my opinion</button>
                    <button type="button" class="btn btn-secondary" onclick="location.href='@Url.Action("Details", "Gaming", new { id = Model.ProductId} )'">Cancel</button>
                </div>
                
            </div>
        </form>
    </div>
</div>

store/store_frontend/Views/Gaming/Xbox.cshtml
@model IEnumerable<StoreFrontendFinal.Models.Product>

@{
    ViewData["Title"] = "Xbox";
}

<div class="image-container">
    <img src="~/images/banner-xbox.jpg" alt="Image description">
    <div class="image-text">
        <p>@ViewData["Title"]</p>
    </div>
</div>


<table>
    <thead>
        <tr>
            <th></th>
            <th>
                Picture
            </th>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.brand)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td></td>
                <td>
                    <img src="@item.image" width="100" height="100" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.price)€
                </td>
                <td>
                    @if (item.brand != null)
                    {
                        @Html.DisplayFor(modelItem => item.brand.name)
                    }
                </td>
                <td>
                    <button class="view-btn" onclick="location.href = '@Url.ActionLink("Details", "Gaming", new { id=item.id })'">
                        <i class="fa fa-eye"></i>
                        View
                    </button>
                </td>
            </tr>
        }
    </tbody>
</table>